#!/bin/bash
set -e

CONTROLLER="slurm-controller"
NODES=("slurm-node1" "slurm-node2")
ALL_VMS=("$CONTROLLER" "${NODES[@]}")

# ── Helper: run a command inside a VM ────────────────────────────────────────
run() { multipass exec "$1" -- bash -c "$2"; }
sudo_run() { multipass exec "$1" -- sudo bash -c "$2"; }

echo "===> Collecting VM IPs..."
CONTROLLER_IP=$(multipass info "$CONTROLLER" | awk '/IPv4/ {print $2}')
NODE1_IP=$(multipass info "slurm-node1"  | awk '/IPv4/ {print $2}')
NODE2_IP=$(multipass info "slurm-node2"  | awk '/IPv4/ {print $2}')
echo "  controller : $CONTROLLER_IP"
echo "  slurm-node1: $NODE1_IP"
echo "  slurm-node2: $NODE2_IP"

# ── 1. Install packages ───────────────────────────────────────────────────────
echo "===> Installing munge on all nodes..."
for vm in "${ALL_VMS[@]}"; do
  sudo_run "$vm" "apt-get install -y munge"
done

echo "===> Installing slurmctld on controller..."
sudo_run "$CONTROLLER" "apt-get install -y slurmctld"

echo "===> Installing slurmd on compute nodes..."
for node in "${NODES[@]}"; do
  sudo_run "$node" "apt-get install -y slurmd"
done

# ── 2. Munge key ─────────────────────────────────────────────────────────────
echo "===> Generating munge key on controller..."
sudo_run "$CONTROLLER" "create-munge-key -r -f"
sudo_run "$CONTROLLER" "chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key"

echo "===> Distributing munge key to compute nodes..."
MUNGE_B64=$(multipass exec "$CONTROLLER" -- sudo cat /etc/munge/munge.key | base64 -w0)
for node in "${NODES[@]}"; do
  echo "$MUNGE_B64" | multipass exec "$node" -- sudo bash -c \
    'base64 -d > /etc/munge/munge.key && chown munge:munge /etc/munge/munge.key && chmod 400 /etc/munge/munge.key'
done

# ── 3. Directories ───────────────────────────────────────────────────────────
echo "===> Creating Slurm directories..."
sudo_run "$CONTROLLER" "mkdir -p /var/spool/slurmctld /var/log/slurm && chown slurm:slurm /var/spool/slurmctld /var/log/slurm"
for node in "${NODES[@]}"; do
  sudo_run "$node" "mkdir -p /var/spool/slurmd /var/log/slurm && chown slurm:slurm /var/spool/slurmd /var/log/slurm"
done

# ── 4. Detect CPU counts ─────────────────────────────────────────────────────
NODE1_CPUS=$(run "slurm-node1" "nproc")
NODE2_CPUS=$(run "slurm-node2" "nproc")
echo "  slurm-node1 CPUs: $NODE1_CPUS"
echo "  slurm-node2 CPUs: $NODE2_CPUS"

# ── 5. Deploy slurm.conf to all nodes ────────────────────────────────────────
echo "===> Deploying slurm.conf..."
SLURM_CONF="# slurm.conf — generated by configure-slurm.sh
ClusterName=multipass-cluster
SlurmctldHost=slurm-controller

AuthType=auth/munge
CryptoType=crypto/munge

MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=2

SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818

SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld

SwitchType=switch/none
TaskPlugin=task/affinity

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

AccountingStorageType=accounting_storage/none
JobAcctGatherType=jobacct_gather/none

SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

NodeName=slurm-node1 NodeAddr=$NODE1_IP CPUs=$NODE1_CPUS State=UNKNOWN
NodeName=slurm-node2 NodeAddr=$NODE2_IP CPUs=$NODE2_CPUS State=UNKNOWN

PartitionName=debug Nodes=slurm-node1,slurm-node2 Default=YES MaxTime=INFINITE State=UP"

for vm in "${ALL_VMS[@]}"; do
  echo "$SLURM_CONF" | multipass exec "$vm" -- sudo bash -c 'mkdir -p /etc/slurm && cat > /etc/slurm/slurm.conf'
done

# ── 6. Start services ─────────────────────────────────────────────────────────
echo "===> Starting munge and slurmctld on controller..."
sudo_run "$CONTROLLER" "systemctl enable munge slurmctld && systemctl restart munge && systemctl restart slurmctld"

echo "===> Starting munge and slurmd on compute nodes..."
for node in "${NODES[@]}"; do
  sudo_run "$node" "systemctl enable munge slurmd && systemctl restart munge && systemctl restart slurmd"
done

echo "===> Done. Slurm cluster configured."
